In [6]:
import pandas as pd
# load the data
df = pd.read_excel('Online_Retail.xlsx')

In [46]:
df.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
21604,538095,22809,SET OF 6 T-LIGHTS SANTA,2,2010-12-09 14:55:00,2.95,17097.0,Spain,5.90
199080,554083,21866,UNION JACK FLAG LUGGAGE TAG,3,2011-05-22 11:51:00,1.25,18125.0,United Kingdom,3.75
89980,543981,22781,GUMBALL MAGAZINE RACK,2,2011-02-15 08:18:00,7.65,15358.0,United Kingdom,15.30
58554,541253,84849D,HOT BATHS SOAP HOLDER,1,2011-01-16 13:51:00,1.69,17841.0,United Kingdom,1.69
425859,573340,22994,TRAVEL CARD WALLET RETROSPOT,4,2011-10-30 11:55:00,0.42,14159.0,United Kingdom,1.68
388182,570420,20969,RED FLORAL FELTCRAFT SHOULDER BAG,2,2011-10-10 13:33:00,3.75,17841.0,United Kingdom,7.50
277761,561192,21876,POTTERING MUG,4,2011-07-25 13:45:00,1.25,16033.0,United Kingdom,5.00
246069,558679,22144,CHRISTMAS CRAFT LITTLE FRIENDS,1,2011-07-01 10:58:00,2.10,17800.0,United Kingdom,2.10
89864,543978,20725,LUNCH BAG RED RETROSPOT,3,2011-02-14 15:37:00,1.65,12867.0,United Kingdom,4.95
454065,575508,22759,SET OF 3 NOTEBOOKS IN PARCEL,96,2011-11-10 10:32:00,1.45,14646.0,Netherlands,139.20

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [12]:
df.dropna(inplace=True)

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   Description  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      401604 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.6+ MB

In [21]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

C:\Users\rahul\AppData\Local\Temp\ipykernel_9444\727825892.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [22]:
df.sample(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
344679,567094,21364,PEACE SMALL WOOD LETTERS,1,2011-09-16 12:54:00,6.75,16924.0,United Kingdom,6.75
384761,570179,20969,RED FLORAL FELTCRAFT SHOULDER BAG,4,2011-10-07 14:27:00,3.75,17509.0,United Kingdom,15.00
389551,570479,22659,LUNCH BOX I LOVE LONDON,3,2011-10-10 16:58:00,1.95,17589.0,United Kingdom,5.85
505910,579103,21892,TRADITIONAL WOODEN CATCH CUP GAME,1,2011-11-28 11:39:00,1.25,18041.0,United Kingdom,1.25
208392,555110,21925,UNION STRIPE CUSHION COVER,1,2011-05-31 14:34:00,1.25,17841.0,United Kingdom,1.25

In [24]:
# listing out catagorical columns
cat_cols = df.select_dtypes(include=['object']).columns

print("Categorical columns:", cat_cols.tolist())

Categorical columns: ['InvoiceNo', 'StockCode', 'Description', 'Country']

In [27]:
df['Description'].value_counts().head(20)

Description
WHITE HANGING HEART T-LIGHT HOLDER    2016
REGENCY CAKESTAND 3 TIER              1714
JUMBO BAG RED RETROSPOT               1615
ASSORTED COLOUR BIRD ORNAMENT         1395
PARTY BUNTING                         1390
LUNCH BAG RED RETROSPOT               1303
SET OF 3 CAKE TINS PANTRY DESIGN      1152
POSTAGE                               1099
LUNCH BAG  BLACK SKULL.               1078
PACK OF 72 RETROSPOT CAKE CASES       1050
SPOTTY BUNTING                        1014
PAPER CHAIN KIT 50'S CHRISTMAS        1003
LUNCH BAG SPACEBOY DESIGN              993
HEART OF WICKER SMALL                  979
LUNCH BAG CARS BLUE                    977
NATURAL SLATE HEART CHALKBOARD         972
LUNCH BAG PINK POLKADOT                941
LUNCH BAG SUKI DESIGN                  915
REX CASH+CARRY JUMBO SHOPPER           897
ALARM CLOCK BAKELIKE RED               886
Name: count, dtype: int64

In [28]:
df['Country'].value_counts().head(20)

Country
United Kingdom     349227
Germany              9027
France               8327
EIRE                 7228
Spain                2480
Netherlands          2363
Belgium              2031
Switzerland          1842
Portugal             1453
Australia            1184
Norway               1072
Italy                 758
Channel Islands       747
Finland               685
Cyprus                603
Sweden                450
Austria               398
Denmark               380
Poland                330
Japan                 321
Name: count, dtype: int64

In [30]:
df['CustomerID'].value_counts().head(20)

CustomerID
17841.0    7676
14911.0    5672
14096.0    5111
12748.0    4413
14606.0    2677
15311.0    2366
14646.0    2080
13089.0    1814
13263.0    1667
14298.0    1637
15039.0    1477
14156.0    1395
18118.0    1263
14159.0    1175
14796.0    1132
16033.0    1128
15005.0    1112
14056.0    1088
14769.0    1062
13081.0    1028
Name: count, dtype: int64

In [29]:
# finding out numerical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
print("Numerical columns:", num_cols.tolist())

Numerical columns: ['Quantity', 'UnitPrice', 'CustomerID', 'Revenue']

In [31]:
df['Quantity'].mean()

np.float64(13.15371805709746)

In [32]:
df['Revenue'].mean()

np.float64(22.629194702748958)

In [47]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID,Revenue
count,392732.000000,392732,392732.000000,392732.000000,392732.000000
mean,13.153718,2011-07-10 19:15:24.576301568,3.125596,15287.734822,22.629195
min,1.000000,2010-12-01 08:26:00,0.000000,12346.000000,0.000000
25%,2.000000,2011-04-07 11:12:00,1.250000,13955.000000,4.950000
50%,6.000000,2011-07-31 12:02:00,1.950000,15150.000000,12.390000
75%,12.000000,2011-10-20 12:53:00,3.750000,16791.000000,19.800000
max,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000,168469.600000
std,181.588420,NaN,22.240725,1713.567773,311.083465

In [52]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [54]:
df.to_csv('cleaned_online_retail.csv', index=False)

In [55]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Revenue'],
      dtype='object')